<a href="https://colab.research.google.com/github/Sushant-ctrl/ALPR/blob/master/Accenture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
mobility_dataset = pd.read_csv("/content/drive/MyDrive/dataset/CovidDataset.csv")

In [3]:
mobility_dataset

      iso_code continent  ... human_development_index excess_mortality
0          AFG      Asia  ...                   0.511              NaN
1          AFG      Asia  ...                   0.511              NaN
2          AFG      Asia  ...                   0.511              NaN
3          AFG      Asia  ...                   0.511              NaN
4          AFG      Asia  ...                   0.511              NaN
...        ...       ...  ...                     ...              ...
97121      ZWE    Africa  ...                   0.571              NaN
97122      ZWE    Africa  ...                   0.571              NaN
97123      ZWE    Africa  ...                   0.571              NaN
97124      ZWE    Africa  ...                   0.571              NaN
97125      ZWE    Africa  ...                   0.571              NaN

[97126 rows x 60 columns]

In [4]:
covid_dataset = pd.read_csv("/content/drive/MyDrive/dataset/mobility.csv")
covid_dataset

        Unnamed: 0               country  ... workplaces residential
0                0  United Arab Emirates  ...        2.0         1.0
1                1  United Arab Emirates  ...        2.0         1.0
2                2  United Arab Emirates  ...        2.0         1.0
3                3  United Arab Emirates  ...        2.0         1.0
4                4  United Arab Emirates  ...        2.0         1.0
...            ...                   ...  ...        ...         ...
310337      310337              Zimbabwe  ...       -4.0         NaN
310338      310338              Zimbabwe  ...      -11.0         NaN
310339      310339              Zimbabwe  ...      -11.0         NaN
310340      310340              Zimbabwe  ...      -11.0         NaN
310341      310341              Zimbabwe  ...       13.0         NaN

[310342 rows x 10 columns]